// Code generated by MockGen. DO NOT EDIT.
// Source: ./client.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/docker_client_mock.go -package=mocks -source=./client.go UnderlyingDockerClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	docker "devmux/internal/docker"
	reflect "reflect"

	types "github.com/docker/docker/api/types"
	container "github.com/docker/docker/api/types/container"
	gomock "go.uber.org/mock/gomock"
)

// MockUnderlyingDockerClient is a mock of UnderlyingDockerClient interface.
type MockUnderlyingDockerClient struct {
	ctrl     *gomock.Controller
	recorder *MockUnderlyingDockerClientMockRecorder
	isgomock struct{}
}

// MockUnderlyingDockerClientMockRecorder is the mock recorder for MockUnderlyingDockerClient.
type MockUnderlyingDockerClientMockRecorder struct {
	mock *MockUnderlyingDockerClient
}

// NewMockUnderlyingDockerClient creates a new mock instance.
func NewMockUnderlyingDockerClient(ctrl *gomock.Controller) *MockUnderlyingDockerClient {
	mock := &MockUnderlyingDockerClient{ctrl: ctrl}
	mock.recorder = &MockUnderlyingDockerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnderlyingDockerClient) EXPECT() *MockUnderlyingDockerClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockUnderlyingDockerClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockUnderlyingDockerClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockUnderlyingDockerClient)(nil).Close))
}

// ContainerInspect mocks base method.
func (m *MockUnderlyingDockerClient) ContainerInspect(ctx context.Context, containerID string) (container.InspectResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerInspect", ctx, containerID)
	ret0, _ := ret[0].(container.InspectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerInspect indicates an expected call of ContainerInspect.
func (mr *MockUnderlyingDockerClientMockRecorder) ContainerInspect(ctx, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerInspect", reflect.TypeOf((*MockUnderlyingDockerClient)(nil).ContainerInspect), ctx, containerID)
}

// ContainerList mocks base method.
func (m *MockUnderlyingDockerClient) ContainerList(ctx context.Context, options container.ListOptions) ([]container.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerList", ctx, options)
	ret0, _ := ret[0].([]container.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerList indicates an expected call of ContainerList.
func (mr *MockUnderlyingDockerClientMockRecorder) ContainerList(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerList", reflect.TypeOf((*MockUnderlyingDockerClient)(nil).ContainerList), ctx, options)
}

// Ping mocks base method.
func (m *MockUnderlyingDockerClient) Ping(ctx context.Context) (types.Ping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(types.Ping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ping indicates an expected call of Ping.
func (mr *MockUnderlyingDockerClientMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockUnderlyingDockerClient)(nil).Ping), ctx)
}

// MockDockerAPI is a mock of DockerAPI interface.
type MockDockerAPI struct {
	ctrl     *gomock.Controller
	recorder *MockDockerAPIMockRecorder
	isgomock struct{}
}

// MockDockerAPIMockRecorder is the mock recorder for MockDockerAPI.
type MockDockerAPIMockRecorder struct {
	mock *MockDockerAPI
}

// NewMockDockerAPI creates a new mock instance.
func NewMockDockerAPI(ctrl *gomock.Controller) *MockDockerAPI {
	mock := &MockDockerAPI{ctrl: ctrl}
	mock.recorder = &MockDockerAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDockerAPI) EXPECT() *MockDockerAPIMockRecorder {
	return m.recorder
}

// CheckHealth mocks base method.
func (m *MockDockerAPI) CheckHealth(ctx context.Context) docker.HealthCheckResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckHealth", ctx)
	ret0, _ := ret[0].(docker.HealthCheckResult)
	return ret0
}

// CheckHealth indicates an expected call of CheckHealth.
func (mr *MockDockerAPIMockRecorder) CheckHealth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckHealth", reflect.TypeOf((*MockDockerAPI)(nil).CheckHealth), ctx)
}

// Close mocks base method.
func (m *MockDockerAPI) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDockerAPIMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDockerAPI)(nil).Close))
}
